CREATE TABLE IF NOT EXISTS schema_migrations(version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,name text NOT NULL,slug text NOT NULL UNIQUE,event_date date NOT NULL,event_time time NOT NULL,timezone text NOT NULL DEFAULT 'America/Sao_Paulo',venue_name text NOT NULL,venue_address text NOT NULL,status text NOT NULL DEFAULT 'active',lifecycle jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE invitations(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,event_id bigint NOT NULL REFERENCES events,display_name text NOT NULL,type text NOT NULL CHECK(type IN ('individual','couple','family','group')),token_hash text NOT NULL UNIQUE CHECK(length(token_hash)=64),max_guests integer NOT NULL CHECK(max_guests BETWEEN 1 AND 100),active boolean NOT NULL DEFAULT true,expires_at timestamptz,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,event_id));
CREATE TABLE guests(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,event_id bigint NOT NULL REFERENCES events,invitation_id bigint NOT NULL,first_name text,last_name text,phone text,email text,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(invitation_id,event_id) REFERENCES invitations(id,event_id));
CREATE TABLE rsvps(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,event_id bigint NOT NULL REFERENCES events,invitation_id bigint NOT NULL UNIQUE,status text NOT NULL CHECK(status IN ('confirmed','declined')),confirmed_guests integer NOT NULL CHECK(confirmed_guests>=0),phone text,notes text,confirmed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(invitation_id,event_id) REFERENCES invitations(id,event_id),CHECK((status='declined' AND confirmed_guests=0) OR (status='confirmed' AND confirmed_guests>0)));
CREATE TABLE rsvp_participants(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,rsvp_id bigint NOT NULL REFERENCES rsvps ON DELETE CASCADE,name text NOT NULL CHECK(length(name) BETWEEN 2 AND 120),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION enforce_capacity() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
IF NEW.confirmed_guests > (SELECT max_guests FROM invitations WHERE id=NEW.invitation_id FOR UPDATE) THEN RAISE EXCEPTION 'Invitation capacity exceeded'; END IF; RETURN NEW; END $$;
CREATE TRIGGER rsvp_capacity BEFORE INSERT OR UPDATE ON rsvps FOR EACH ROW EXECUTE FUNCTION enforce_capacity();
CREATE FUNCTION protect_capacity() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
IF NEW.max_guests < COALESCE((SELECT confirmed_guests FROM rsvps WHERE invitation_id=NEW.id),0) THEN RAISE EXCEPTION 'Capacity below current RSVP'; END IF; RETURN NEW; END $$;
CREATE TRIGGER invitation_capacity BEFORE UPDATE OF max_guests ON invitations FOR EACH ROW EXECUTE FUNCTION protect_capacity();
CREATE TABLE gift_categories(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,event_id bigint NOT NULL REFERENCES events,name text NOT NULL,slug text NOT NULL,sort_order integer NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,UNIQUE(event_id,slug),UNIQUE(id,event_id));
CREATE TABLE gifts(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,event_id bigint NOT NULL REFERENCES events,category_id bigint NOT NULL,name text NOT NULL,brand text NOT NULL,description text,image_url text,external_url text,size text,sort_order integer NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(category_id,event_id) REFERENCES gift_categories(id,event_id));
CREATE TABLE photo_albums(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,event_id bigint NOT NULL REFERENCES events,name text NOT NULL,slug text NOT NULL,description text,cover_image text,sort_order integer NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(event_id,slug));
CREATE TABLE photos(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,album_id bigint NOT NULL REFERENCES photo_albums,title text,description text,image_url text NOT NULL,thumbnail_url text,sort_order integer NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,taken_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX photos_album_order ON photos(album_id,sort_order);
CREATE INDEX participants_rsvp ON rsvp_participants(rsvp_id);
INSERT INTO events(name,slug,event_date,event_time,venue_name,venue_address) VALUES('Anna Sophie — XV Anos','anna-sophie-xv','2026-12-06','18:15','Estação 840','Avenida Marechal Rondon, 840 — Centro, Osasco/SP');