import ExcelJS from 'exceljs';import {database,EVENT_SLUG} from '../db';import {generateToken,hashToken} from '../tokens';import {encryptToken} from './token-vault';import {audit} from './audit';
export type ImportRow={display_name:string;type:string;phone:string;expected_guests:number;max_guests:number;invitation_round:number;rsvp_deadline:string|null;participants:string[];notes:string;line:number;errors:string[]};
const columns=['display_name','type','phone','expected_guests','max_guests','invitation_round','rsvp_deadline','participant_1','participant_2','participant_3','participant_4','participant_5','notes'];
function csvRows(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===','&&!quoted){row.push(cell);cell=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=char}row.push(cell);if(row.some(Boolean))rows.push(row);return rows;}
function valuesToObjects(values:unknown[][]){const headers=values[0]?.map(v=>String(v||'').trim())||[];return values.slice(1).map(line=>Object.fromEntries(headers.map((h,i)=>[h,line[i]??''])));}
export async function parseImport(buffer:ArrayBuffer,filename:string):Promise<ImportRow[]>{let raw:Record<string,unknown>[];if(filename.toLowerCase().endsWith('.csv'))raw=valuesToObjects(csvRows(new TextDecoder().decode(buffer)));else{const book=new ExcelJS.Workbook();await book.xlsx.load(buffer);const sheet=book.worksheets[0];if(!sheet)throw new Error('Planilha vazia.');const values:unknown[][]=[];sheet.eachRow(row=>values.push((row.values as unknown[]).slice(1)));raw=valuesToObjects(values)}return raw.map((r,index)=>{const row:ImportRow={display_name:String(r.display_name||'').trim(),type:String(r.type||'').trim().toLowerCase(),phone:String(r.phone||'').trim(),expected_guests:Number(r.expected_guests),max_guests:Number(r.max_guests),invitation_round:Number(r.invitation_round),rsvp_deadline:r.rsvp_deadline?String(r.rsvp_deadline):null,participants:[1,2,3,4,5].map(i=>String(r[`participant_${i}`]||'').trim()).filter(Boolean),notes:String(r.notes||'').trim(),line:index+2,errors:[]};if(!row.display_name)row.errors.push('Nome obrigatório');if(!['individual','couple','family','group'].includes(row.type))row.errors.push('Tipo inválido');if(!Number.isInteger(row.expected_guests)||row.expected_guests<1)row.errors.push('Previstos inválido');if(!Number.isInteger(row.max_guests)||row.max_guests<1||row.max_guests>100)row.errors.push('Limite inválido');if(!Number.isInteger(row.invitation_round)||row.invitation_round<1)row.errors.push('Rodada inválida');if(row.rsvp_deadline&&!Number.isFinite(Date.parse(row.rsvp_deadline)))row.errors.push('Prazo inválido');return row})}
export async function validateDuplicates(rows:ImportRow[]){const seen=new Set<string>();for(const row of rows){const key=(row.display_name+'|'+row.phone).toLowerCase();if(seen.has(key))row.errors.push('Duplicado no arquivo');seen.add(key);const exists=await database().query('SELECT 1 FROM invitations i JOIN events e ON e.id=i.event_id WHERE e.slug=$1 AND lower(i.display_name)=lower($2) AND COALESCE(i.phone,\'\')=$3 LIMIT 1',[EVENT_SLUG,row.display_name,row.phone]);if(exists.rowCount)row.errors.push('Já existe no banco')}return rows}
export async function importRows(rows:ImportRow[],userId:number){if(rows.some(r=>r.errors.length))throw new Error('Corrija as linhas inválidas antes de importar.');const client=await database().connect();try{await client.query('BEGIN');const event=(await client.query('SELECT id FROM events WHERE slug=$1 FOR UPDATE',[EVENT_SLUG])).rows[0];for(const row of rows){const token=generateToken();const invitation=(await client.query(`INSERT INTO invitations(event_id,display_name,type,phone,expected_guests,max_guests,invitation_round,rsvp_deadline,token_hash,token_ciphertext,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`,[event.id,row.display_name,row.type,row.phone,row.expected_guests,row.max_guests,row.invitation_round,row.rsvp_deadline,hashToken(token),encryptToken(token),row.notes])).rows[0];for(const name of row.participants)await client.query('INSERT INTO guests(event_id,invitation_id,first_name,is_expected) VALUES($1,$2,$3,true)',[event.id,invitation.id,name])}await audit(client,userId,'IMPORT_INVITATIONS','invitation',null,null,{count:rows.length});await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
const safe=(value:unknown)=>{const text=String(value??'');return /^[=+\-@]/.test(text)?"'"+text:text};
export async function exportData(){const {rows}=await database().query(`SELECT i.display_name "Convite",i.invitation_round "Rodada",i.type "Tipo",i.phone "Telefone",i.expected_guests "Previstos",i.max_guests "Limite",COALESCE(r.confirmed_guests,0) "Confirmados",COALESCE((SELECT count(*) FROM rsvp_participants p WHERE p.rsvp_id=r.id AND p.age_band='0_7'),0)::int "0 a 7 anos",COALESCE((SELECT count(*) FROM rsvp_participants p WHERE p.rsvp_id=r.id AND p.age_band='8_12'),0)::int "8 a 12 anos",GREATEST(0,COALESCE(r.confirmed_guests,0)-COALESCE((SELECT count(*) FROM rsvp_participants p WHERE p.rsvp_id=r.id AND p.age_band IS NOT NULL),0))::int "13 anos ou mais",i.rsvp_deadline "Prazo RSVP",CASE WHEN i.revoked_at IS NOT NULL THEN 'Revogado' WHEN r.status='confirmed' THEN 'Confirmado' WHEN r.status IN ('declined','cancelled') THEN 'Não irá' ELSE 'Pendente' END "Status",i.delivered_at "Entregue em",i.first_viewed_at "Primeira visualização",i.last_viewed_at "Última visualização",i.responded_at "Respondido em",COALESCE((SELECT string_agg(p.name||' ('||CASE p.age_band WHEN '0_7' THEN '0 a 7 anos' WHEN '8_12' THEN '8 a 12 anos' ELSE '13 anos ou mais' END||')',', ' ORDER BY p.id) FROM rsvp_participants p WHERE p.rsvp_id=r.id),'') "Participantes",i.notes "Observações" FROM invitations i JOIN events e ON e.id=i.event_id LEFT JOIN rsvps r ON r.invitation_id=i.id WHERE e.slug=$1 ORDER BY i.invitation_round,i.display_name`,[EVENT_SLUG]);return rows.map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,safe(value)])))}
export function csvBuffer(rows:any[]){const headers=rows[0]?Object.keys(rows[0]):[];const quote=(v:unknown)=>'"'+String(v??'').replaceAll('"','""')+'"';return Buffer.from('\ufeff'+[headers.map(quote).join(','),...rows.map(row=>headers.map(h=>quote(row[h])).join(','))].join('\r\n'),'utf8')}
async function workbookBuffer(headers:string[],rows:any[][]){const book=new ExcelJS.Workbook();const sheet=book.addWorksheet('Convites');sheet.addRow(headers);for(const row of rows)sheet.addRow(row);sheet.getRow(1).font={bold:true};sheet.columns.forEach(column=>column.width=20);return Buffer.from(await book.xlsx.writeBuffer())}
export async function xlsxBuffer(rows:any[]){const headers=rows[0]?Object.keys(rows[0]):[];return workbookBuffer(headers,rows.map(row=>headers.map(h=>row[h])))}
export async function templateBuffer(){return workbookBuffer(columns,[])}
